"""fix_project_user_autoincrement

Revision ID: 844182b3bb25
Revises: 99047bfcd345
Create Date: 2026-03-06 05:13:25.570206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844182b3bb25'
down_revision: Union[str, None] = '99047bfcd345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###