"""initial_with_projects

Revision ID: 99047bfcd345
Revises: 
Create Date: 2026-03-05 09:37:44.523832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99047bfcd345'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workplaces_workplace_id', table_name='workplaces')
    op.drop_table('workplaces')
    op.drop_constraint('columns_project_id_fkey', 'columns', type_='foreignkey')
    op.create_foreign_key(None, 'columns', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.add_column('project_users', sa.Column('project_user_id', sa.Integer(), nullable=False))
    op.add_column('project_users', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('project_users', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_project_users_project_user_id'), 'project_users', ['project_user_id'], unique=False)
    op.drop_constraint('project_users_project_id_fkey', 'project_users', type_='foreignkey')
    op.drop_constraint('project_users_user_id_fkey', 'project_users', type_='foreignkey')
    op.create_foreign_key(None, 'project_users', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_users', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['user_id'])
    op.drop_column('projects', 'workplace_id')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('projects', sa.Column('workplace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'created_by')
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.create_foreign_key('project_users_user_id_fkey', 'project_users', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('project_users_project_id_fkey', 'project_users', 'projects', ['project_id'], ['project_id'])
    op.drop_index(op.f('ix_project_users_project_user_id'), table_name='project_users')
    op.alter_column('project_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_users', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('project_users', 'joined_at')
    op.drop_column('project_users', 'project_user_id')
    op.drop_constraint(None, 'columns', type_='foreignkey')
    op.create_foreign_key('columns_project_id_fkey', 'columns', 'projects', ['project_id'], ['project_id'])
    op.create_table('workplaces',
    sa.Column('workplace_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workplace_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='workplaces_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workplace_id', name='workplaces_pkey')
    )
    op.create_index('ix_workplaces_workplace_id', 'workplaces', ['workplace_id'], unique=False)
    # ### end Alembic commands ###