"""change_focus_time_to_integer

Revision ID: c6023d0b4184
Revises: 844182b3bb25
Create Date: 2026-03-11 15:20:42.361339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6023d0b4184'
down_revision: Union[str, None] = '844182b3bb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'focus_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'focus_time',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###